# Generated by Django 4.0 on 2021-12-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('LanguageId', models.AutoField(primary_key=True, serialize=False)),
                ('LanguageName', models.CharField(blank=True, max_length=50, null=True)),
                ('LanguageNameInEnglish', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
